### ISSUE TITLE
Dataset details

### ISSUE THREAD

**Issue by haofanwang** [dangeng/visual_anagrams#1]
Interesting work!

Is there any plan to release the training dataset and code?

**Comment by dangeng** [comment]
Hey, thanks!

We don't actually do any training. We just use pretrained off-the-shelf diffusion models (in particular [DeepFloyd IF](https://huggingface.co/docs/diffusers/api/pipelines/deepfloyd_if)).

Actually, I might be wrong, but I don't think there's that many of these multi-view optical illusions in the wild. Maybe a few hundred, if that? You would be hard pressed to make a dataset large enough to train a model. Which I think makes this method quite interesting!
