### ISSUE TITLE
NameError: name 'stage_1' is not defined

### ISSUE THREAD

**Issue by raynt** [dangeng/visual_anagrams#12]
When running the cell:

`image_64 = sample_stage_1(stage_1,
                          prompt_embeds,
                          negative_prompt_embeds,
                          views,
                          num_inference_steps=30,
                          guidance_scale=10.0,
                          reduction='mean',
                          generator=None)
mp.show_images([im_to_np(view.view(image_64[0])) for view in views])`

There is an error:

NameError                                 Traceback (most recent call last)
[<ipython-input-8-e797bb6ab265>](https://localhost:8080/#) in <cell line: 1>()
----> 1 image_64 = sample_stage_1(stage_1,
      2                           prompt_embeds,
      3                           negative_prompt_embeds,
      4                           views,
      5                           num_inference_steps=30,

NameError: name 'stage_1' is not defined

**Comment by dangeng** [comment]
Hey! It looks like the `stage_1` object (the first stage of DeepFloyd IF) was never created. You might have missed one of the cells while running the notebook (in particular, the one with the comment `# Load DeepFloyd IF stage I`). If you just restart your runtime and run all of the cells consecutively, I think this error should go away. 

I'm going to close this issue now, but please comment if you have any other questions or if the above doesn't work.
