### ISSUE TITLE
When is the release date for Facterized Diffusion?

### ISSUE THREAD

**Issue by ryhhtn** [dangeng/visual_anagrams#14]
Thanks for a very interesting paper.

When do you expect to release the code for Facterized Diffusion?
I am very much looking forward to it!

**Comment by dangeng** [comment]
Hello, thanks for giving me the impetus to work on the code! And thanks for your interest!

I've just released the code. The readme is right [here](https://github.com/dangeng/visual_anagrams/blob/main/readme_factorized_diffusion.md), and there's also a [colab notebook](https://colab.research.google.com/drive/1S9v0m9fgAw4MDdsLVHAdaRx94L4dwTPw?usp=sharing) if you're so inclined.

Please let me know if something is broken or if you want any more features!

Best,
Daniel
