### ISSUE TITLE
requirement `clip=-1.0` causing installation failure

### ISSUE THREAD

**Issue by JonasLoos** [dangeng/visual_anagrams#4]
When installing this repository with
```
conda env create -f environment.yml
```
I get the error
```
ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
```

When removing the line [`- clip==1.0`](https://github.com/dangeng/visual_anagrams/blob/bbdc1a8115c30c409df2520a92dc922e4612a283/environment.yml#L169C1-L169C18) from `environment.yml`, it works fine. 

For pip, by default, `clip` refers to an old clipboard manager: https://pypi.org/project/clip/
If you mean OpenAI CLIP, maybe the line should be changed to reference `git+https://github.com/openai/CLIP.git`.

However, because it doesn't seem to be needed, I would suggest removing this line.

**Comment by dangeng** [comment]
Hello, thank you so much for catching this! I've updated the `environment.yml` file.

**Comment by madeline-past** [comment]
Thank you for sharing the solution!

I met the same problem in another repo and managed to fix it following your advice :>)

**Comment by mayenne-tout-court** [comment]
I solved my error:
Use SSH instead of HTTPS (if you have SSH keys set up): pip install git+ssh://git@github.com/openai/CLIP.git
