### ISSUE TITLE
animate.py fails in example case

### ISSUE THREAD

**Issue by drecht** [dangeng/visual_anagrams#5]
Running locally on an NVIDIA 3080 Max-Q with 16 GB VRAM

`python generate.py --name rotate_cw.village.horse --prompts "a snowy mountain village" "a horse" --style "an oil painting of" --views identity rotate_cw --num_samples 10 --num_inference_steps 30 --guidance_scale 10.0`

runs as expected but

`python animate.py --im_path results/rotate_cw.village.horse/0000/sample_256.png --metadata_path results/rotate_cw.village.horse/metadata.pkl`

fails with the error

> 100%|████████████████████████████████████████████████████████████████████████| 45/45 [00:00<00:00, 352.56it/s]
> Making video...
> Traceback (most recent call last):
>   File "/home/dan/anagram/visual_anagrams/animate.py", line 169, in <module>
>     animate_two_view(
>   File "/home/dan/anagram/visual_anagrams/animate.py", line 123, in animate_two_view
>     imageio.mimsave(save_video_path, image_array, fps=30)
>   File "/home/dan/miniconda3/envs/visual_anagrams/lib/python3.9/site-packages/imageio/v2.py", line 494, in mimwrite
>     with imopen(uri, "wI", **imopen_args) as file:
>   File "/home/dan/miniconda3/envs/visual_anagrams/lib/python3.9/site-packages/imageio/core/imopen.py", line 281, in imopen
>     raise err_type(err_msg)
> ValueError: Could not find a backend to open `results/rotate_cw.village.horse/0000/sample_256.mp4`` with iomode `wI`.
> Based on the extension, the following plugins might add capable backends:
>   FFMPEG:  pip install imageio[ffmpeg]
>   pyav:  pip install imageio[pyav]

despite having imageio with the ffmpeg and pyav plugins installed in the conda environment.

**Comment by dangeng** [comment]
I think I ran into a similar error at one point. I solved it by uninstalling `imageio` from the conda env, and re-installing by running `pip install imageio[ffmpeg]`. As a fallback, you could just save all the images in the `image_array` to a file, and run `ffmpeg` on the images to generate a video. Please let me know if this helps!
