### ISSUE TITLE
Issue creating conda environment with freshly cloned repository

### ISSUE THREAD

**Issue by chriscarm** [dangeng/visual_anagrams#6]
Hello, I'm running into an issue when cloning the repository and following the steps to install the conda environment. I've pasted the output below. Any help that you can provide is appreciated!

- os: macos/arm64
- conda version: 23.10.0
- python: 3.11.5

```sh
conda env create -f environment.yml            
Channels:
 - pytorch
 - nvidia
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - _libgcc_mutex==0.1=main
  - _openmp_mutex==5.1=1_gnu
  - blas==1.0=mkl
  - bottleneck==1.3.5=py39h7deecbd_0
  - brotli==1.0.9=h9c3ff4c_4
  - brotlipy==0.7.0=py39h27cfd23_1003
  - bzip2==1.0.8=h7b6447c_0
  - ca-certificates==2023.7.22=hbcca054_0
  - cffi==1.15.1=py39h5eee18b_3
  - contourpy==1.0.5=py39hdb19cb5_0
  - cryptography==41.0.3=py39hdda0065_0
  - cuda-cudart==12.1.105=0
  - cuda-cupti==12.1.105=0
  - cuda-libraries==12.1.0=0
  - cuda-nvrtc==12.1.105=0
  - cuda-nvtx==12.1.105=0
  - cuda-opencl==12.2.140=0
  - cuda-runtime==12.1.0=0
  - cyrus-sasl==2.1.28=h52b45da_1
  - dbus==1.13.18=hb2f20db_0
  - expat==2.5.0=h6a678d5_0
  - ffmpeg==4.3=hf484d3e_0
  - fontconfig==2.14.1=h4c34cd2_2
  - freetype==2.12.1=h4a9f257_0
  - giflib==5.2.1=h5eee18b_3
  - glib==2.69.1=he621ea3_2
  - gmp==6.2.1=h295c915_3
  - gmpy2==2.1.2=py39heeb90bb_0
  - gnutls==3.6.15=he1e5248_0
  - gst-plugins-base==1.14.1=h6a678d5_1
  - gstreamer==1.14.1=h5eee18b_1
  - icu==58.2=hf484d3e_1000
  - idna==3.4=py39h06a4308_0
  - intel-openmp==2023.1.0=hdb19cb5_46305
  - jinja2==3.1.2=py39h06a4308_0
  - jpeg==9e=h5eee18b_1
  - kiwisolver==1.4.4=py39h6a678d5_0
  - krb5==1.20.1=h143b758_1
  - lame==3.100=h7b6447c_0
  - lcms2==2.12=h3be6417_0
  - ld_impl_linux-64==2.38=h1181459_1
  - lerc==3.0=h295c915_0
  - libclang==14.0.6=default_hc6dbbc7_1
  - libclang13==14.0.6=default_he11475f_1
  - libcublas==12.1.0.26=0
  - libcufft==11.0.2.4=0
  - libcufile==1.7.2.10=0
  - libcups==2.4.2=h2d74bed_1
  - libcurand==10.3.3.141=0
  - libcusolver==11.4.4.55=0
  - libcusparse==12.0.2.55=0
  - libdeflate==1.17=h5eee18b_1
  - libedit==3.1.20221030=h5eee18b_0
  - libevent==2.1.12=hdbd6064_1
  - libffi==3.4.4=h6a678d5_0
  - libgcc-ng==11.2.0=h1234567_1
  - libgfortran-ng==13.2.0=h69a702a_0
  - libgfortran5==13.2.0=ha4646dd_0
  - libgomp==11.2.0=h1234567_1
  - libiconv==1.16=h7f8727e_2
  - libidn2==2.3.4=h5eee18b_0
  - libjpeg-turbo==2.0.0=h9bf148f_0
  - libllvm14==14.0.6=hdb19cb5_3
  - libnpp==12.0.2.50=0
  - libnvjitlink==12.1.105=0
  - libnvjpeg==12.1.1.14=0
  - libpng==1.6.39=h5eee18b_0
  - libpq==12.15=hdbd6064_1
  - libstdcxx-ng==11.2.0=h1234567_1
  - libtasn1==4.19.0=h5eee18b_0
  - libtiff==4.5.1=h6a678d5_0
  - libunistring==0.9.10=h27cfd23_0
  - libuuid==1.41.5=h5eee18b_0
  - libwebp==1.3.2=h11a3e52_0
  - libwebp-base==1.3.2=h5eee18b_0
  - libxcb==1.15=h7f8727e_0
  - libxkbcommon==1.0.1=h5eee18b_1
  - libxml2==2.10.4=hcbfbd50_0
  - libxslt==1.1.37=h2085143_0
  - llvm-openmp==14.0.6=h9e868ea_0
  - lz4-c==1.9.4=h6a678d5_0
  - matplotlib==3.7.2=py39h06a4308_0
  - matplotlib-base==3.7.2=py39h1128e8f_0
  - mkl==2023.1.0=h213fc3f_46343
  - mkl-service==2.4.0=py39h5eee18b_1
  - mkl_fft==1.3.8=py39h5eee18b_0
  - mkl_random==1.2.4=py39hdb19cb5_0
  - mpc==1.1.0=h10f8cd9_1
  - mpfr==4.0.2=hb69a4c5_1
  - mpmath==1.3.0=py39h06a4308_0
  - mysql==5.7.24=h721c034_2
  - ncurses==6.4=h6a678d5_0
  - nettle==3.7.3=hbbd107a_1
  - networkx==3.1=py39h06a4308_0
  - numexpr==2.8.7=py39h85018f9_0
  - numpy==1.26.0=py39h5f9d8c6_0
  - numpy-base==1.26.0=py39hb5e798b_0
  - openh264==2.1.1=h4ff587b_0
  - openjpeg==2.4.0=h3ad879b_0
  - openssl==3.0.11=h7f8727e_2
  - pandas==2.1.1=py39h1128e8f_0
  - pcre==8.45=h9c3ff4c_0
  - pillow==10.0.1=py39ha6cbd5a_0
  - pip==23.2.1=py39h06a4308_0
  - pyopenssl==23.2.0=py39h06a4308_0
  - pyqt==5.15.7=py39h6a678d5_1
  - pyqt5-sip==12.11.0=py39h6a678d5_1
  - pysocks==1.7.1=py39h06a4308_0
  - python==3.9.18=h955ad1f_0
  - pytorch==2.1.0=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda==12.1=ha16c6d3_5
  - qt-main==5.15.2=h7358343_9
  - qt-webengine==5.15.9=hbbf29b9_6
  - qtwebkit==5.212=h3fafdc1_5
  - readline==8.2=h5eee18b_0
  - requests==2.31.0=py39h06a4308_0
  - scipy==1.11.3=py39h5f9d8c6_0
  - setuptools==68.0.0=py39h06a4308_0
  - sip==6.6.2=py39h6a678d5_0
  - sqlite==3.41.2=h5eee18b_0
  - statsmodels==0.14.0=py39ha9d4c09_0
  - tbb==2021.8.0=hdb19cb5_0
  - tk==8.6.12=h1ccaba5_0
  - torchaudio==2.1.0=py39_cu121
  - torchtriton==2.1.0=py39
  - torchvision==0.16.0=py39_cu121
  - tornado==6.1=py39hb9d737c_3
  - typing_extensions==4.7.1=py39h06a4308_0
  - wheel==0.41.2=py39h06a4308_0
  - xz==5.4.2=h5eee18b_0
  - yaml==0.2.5=h7b6447c_0
  - zlib==1.2.13=h5eee18b_0
  - zstd==1.5.5=hc292b87_0

Current channels:

  - https://conda.anaconda.org/pytorch/osx-arm64
  - https://conda.anaconda.org/nvidia/osx-arm64
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/r/osx-arm64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by SoftologyPro** [comment]
I created my own env (outside anaconda with python -m venv) and used these pip commands to setup the required packages.

```
python -m pip install --upgrade pip
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts wheel==0.41.2
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts accelerate==0.23.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts attrs==23.1.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts chardet==5.2.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts charset-normalizer==3.3.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts clip==0.2.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts diffusers==0.21.4
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts dominate==2.8.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts einops==0.7.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts filelock==3.12.4
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts fsspec==2023.9.2
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts ftfy==6.1.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts huggingface-hub==0.17.3
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts importlib-metadata==6.8.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts kornia==0.7.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts markupsafe==2.1.3
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cublas-cu12==12.1.3.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cuda-cupti-cu12==12.1.105
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cuda-nvrtc-cu12==12.1.105
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cuda-runtime-cu12==12.1.105
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cudnn-cu12==8.9.6.50
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cufft-cu12==11.0.2.54
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-curand-cu12==10.3.2.106
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cusolver-cu12==11.4.5.107
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cusparse-cu12==12.1.0.106
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-nvjitlink-cu12==12.2.140
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-nvtx-cu12==12.1.105
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts psutil==5.9.5
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts pyyaml==6.0.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts regex==2023.10.3
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts safetensors==0.4.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts sentencepiece==0.1.99
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts sympy==1.12
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts tokenizers==0.14.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts tqdm==4.66.1
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts transformers==4.34.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts typing-extensions==4.8.0
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts urllib3==2.0.6
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts wcwidth==0.2.8
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.1.1+cu118 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

Then the generate.py script ran fine.

**Comment by unspokenlanguage** [comment]
> I created my own env (outside anaconda with python -m venv) and used these pip commands to setup the required packages.
> 
> ```
> python -m pip install --upgrade pip
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts wheel==0.41.2
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts accelerate==0.23.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts attrs==23.1.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts chardet==5.2.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts charset-normalizer==3.3.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts clip==0.2.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts diffusers==0.21.4
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts dominate==2.8.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts einops==0.7.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts filelock==3.12.4
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts fsspec==2023.9.2
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts ftfy==6.1.1
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts huggingface-hub==0.17.3
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts importlib-metadata==6.8.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts kornia==0.7.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts markupsafe==2.1.3
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cublas-cu12==12.1.3.1
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cuda-cupti-cu12==12.1.105
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cuda-nvrtc-cu12==12.1.105
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cuda-runtime-cu12==12.1.105
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cudnn-cu12==8.9.6.50
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cufft-cu12==11.0.2.54
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-curand-cu12==10.3.2.106
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cusolver-cu12==11.4.5.107
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-cusparse-cu12==12.1.0.106
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-nvjitlink-cu12==12.2.140
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts nvidia-nvtx-cu12==12.1.105
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts psutil==5.9.5
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts pyyaml==6.0.1
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts regex==2023.10.3
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts safetensors==0.4.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts sentencepiece==0.1.99
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts sympy==1.12
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts tokenizers==0.14.1
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts tqdm==4.66.1
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts transformers==4.34.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts typing-extensions==4.8.0
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts urllib3==2.0.6
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts wcwidth==0.2.8
> pip uninstall -y torch
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.1.1+cu118 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> Then the generate.py script ran fine.

Thank you so much. I will give a try.

**Comment by unspokenlanguage** [comment]
Python pip commands worked perfect. Thanks again.

**Comment by mykeehu** [comment]
> I created my own env (outside anaconda with python -m venv) and used these pip commands to setup the required packages.
> Then the generate.py script ran fine.

Great thanks! I made a requirements.txt file from your guide and I used these steps:
```
python -m venv visual_anagrams
visual_anagrams\Scripts\Activate.bat
python -m pip install --upgrade pip
pip install -r requirements.txt
```
[requirements.txt](https://github.com/dangeng/visual_anagrams/files/13620637/requirements.txt)

**Comment by dangeng** [comment]
Hi, sorry for the delay on this issue. I just pushed a simpler, less bloated `environment.yml` file on commit bb18268. Hopefully it works better, but please let me know if there's any problems!

**Comment by svennidal** [comment]
Tried with the new version. Did not work for me.

**Comment by dangeng** [comment]
@svennidal, can you explain the error in more detail?

**Comment by nikolaiusa** [comment]
> @svennidal,можно подробнее объяснить ошибку?

(base) D:\PUZZLE\visual_anagrams>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ncurses==6.4=h6a678d5_0
  - pip==23.3.1=py39h06a4308_0
  - libgomp==11.2.0=h1234567_1
  - libffi==3.4.4=h6a678d5_0
  - xz==5.4.5=h5eee18b_0
  - python==3.9.18=h955ad1f_0
  - sqlite==3.41.2=h5eee18b_0
  - zlib==1.2.13=h5eee18b_0
  - tk==8.6.12=h1ccaba5_0
  - wheel==0.41.2=py39h06a4308_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - _openmp_mutex==5.1=1_gnu
  - ld_impl_linux-64==2.38=h1181459_1
  - setuptools==68.0.0=py39h06a4308_0
  - openssl==3.0.12=h7f8727e_0
  - libgcc-ng==11.2.0=h1234567_1
  - readline==8.2=h5eee18b_0
  - ca-certificates==2023.08.22=h06a4308_0

**Comment by svennidal** [comment]
> @svennidal, can you explain the error in more detail?

Yes. I can see that my comment wasn't exactly helpful. But here is the output I get:

```
conda env create -f environment.yml
Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - _openmp_mutex==5.1=1_gnu
  - ca-certificates==2023.08.22=h06a4308_0
  - ld_impl_linux-64==2.38=h1181459_1
  - libffi==3.4.4=h6a678d5_0
  - libgcc-ng==11.2.0=h1234567_1
  - libgomp==11.2.0=h1234567_1
  - libstdcxx-ng==11.2.0=h1234567_1
  - ncurses==6.4=h6a678d5_0
  - openssl==3.0.12=h7f8727e_0
  - pip==23.3.1=py39h06a4308_0
  - python==3.9.18=h955ad1f_0
  - readline==8.2=h5eee18b_0
  - setuptools==68.0.0=py39h06a4308_0
  - sqlite==3.41.2=h5eee18b_0
  - tk==8.6.12=h1ccaba5_0
  - wheel==0.41.2=py39h06a4308_0
  - xz==5.4.5=h5eee18b_0
  - zlib==1.2.13=h5eee18b_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/r/osx-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by dangeng** [comment]
Ahh I see. I think the problem is that you're using osx (or windows in the case of @nikolaiusa), and builds and packages specified by the conda env don't exist on those platforms. The code is only tested on linux, with an A40 gpu. I tried messing around a bit, but getting the code to work on a mac is a pain, and you would likely want CUDA and a GPU anyways. I would highly recommend checking out the colab notebook if you want to play with the code.

If you want to try to run on a mac the requirements are roughly:

```
torch
torchvision
diffusers
transformers
sentencepiece 
accelerate
einops
huggingface_hub
imageio
numpy
PIL
tqdm
```

**Comment by nikolaiusa** [comment]
> python -m venv visual_anagrams
> visual_anagrams\Scripts\Activate.bat
> python -m pip install --upgrade pip
> pip install -r requirements.txt
 [requirements.txt](https://github.com/dangeng/visual_anagrams/files/13620637/requirements.txt)

its worked for windows10   (-+ 1 or 2 one pip install ..... something - (when the message module not found appears))
[my gif](https://imgur.com/a/MEJMh6h)


(Thanks, it was interesting to try.)
