### ISSUE TITLE
How to create animations?

### ISSUE THREAD

**Issue by SoftologyPro** [dangeng/visual_anagrams#7]
I can run the example scripts but I only get static dual image results.
How can I generate the animated/rotating gif examples you show in the git repo and https://dangeng.github.io/visual_anagrams/ page.

**Comment by unspokenlanguage** [comment]
> I can run the example scripts but I only get static dual image results. How can I generate the animated/rotating gif examples you show in the git repo and https://dangeng.github.io/visual_anagrams/ page.

How you were able to create environment, as I couldn't' even yet able to run the script as I also had the following issue.
https://github.com/dangeng/visual_anagrams/issues/6

**Comment by SoftologyPro** [comment]
> How you were able to create environment, as I couldn't' even yet able to run the script as I also had the following issue. #6

I answered in your other issue as that has nothing to do with this problem.

**Comment by dangeng** [comment]
Hi! Did you the command in the readme not work for you? The one under the heading `Animating`?

**Comment by SoftologyPro** [comment]
Yes, I did miss that :)  Thanks, it works now.

**Comment by dangeng** [comment]
Great to hear!

(btw, to your previous edits: yeah I definitely think animation could be a bit better. I could add a flag, but might be a waste of disk/compute given that not every illusion you generate you would want to animate. I plan to think about it and push some changes when I find the time)
